site_name: Partho's Blog
site_author: Partho S Bhowmick
site_url: htts://partho.dev
site_description: |
  Partho's blog - all things Kubernetes, dev, Python et al.

theme:
  name: material
  features:
    - navigation.indexes
nav:
  - 'index.md'
watch:
  - docs/posts
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - blog:
      blog_dir: .
      blog_toc: true
      post_date_format: long
      authors_file: "{blog}/.authors.yml"
