---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yaml convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: puml
  name: puml
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: puml
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yaml convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: puml
    spec:
      containers:
        - image: plantuml/plantuml-server
          name: puml
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yaml convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: puml
  name: puml
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 9000
  selector:
    io.kompose.service: puml
---

